path:
  ckpt_path: "./output/ckpt/InFore_mod"
  log_path: "./output/log/InFore"
  result_path: "./output/result/InFore"
optimizer:
  batch_size: 16
  betas: [0.5, 0.9] #[0.5, 0.9]
  eps: 0.0000001 #0.000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [12000, 15000, 18000]
  anneal_rate: 0.3
step:
  total_step: 20000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 2000
